# SonarCloudの設定ファイル
sonar.projectKey=rokushakai_stream-player-web
sonar.organization=rokushakai
# ※上記2行はご自身のGitHubアカウント名に合わせて適宜変更してください（SonarCloudの画面に指定の文字列が表示されています）

sonar.sources=frontend/src,backend/app
sonar.tests=frontend/src,backend/tests
sonar.test.inclusions=**/*.test.*,**/test_*.py
sonar.exclusions=**/node_modules/**,**/*.test.*

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.python.version=3.12